INSERT INTO `muscle_groups` (`id`, `name`) VALUES
(1,	'Pecho'),
(2,	'Espalda'),
(3,	'Bíceps'),
(4,	'Tríceps'),
(5,	'Hombro'),
(6,	'Glúteo'),
(7,	'Femorales'),
(8,	'Isquiotibiales'),
(9,	'Cuádriceps'),
(10,	'Cuádriceps/Femoral'),
(11,	'Pantorrilla'),
(12,	'Pierna'),
(13,	'Core / Abdomen'),
(14,	'Gemelos / Pantorrilla'),
(15,	'Cardio');

INSERT INTO `exercises` (`muscle_group_id`, `name`, `organization`, `method`, `default_sets`, `default_reps`, `default_rest_sec`, `notes`, `tracking_type`) VALUES
(1,	'Press declinado con barra olímpica',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Cables en la jaula con inclinación de tronco',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press banco inclinado con mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Elevación frontal con barra agarre abierto',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Press francés con barra Z en banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensiones unilaterales con agarre neutro polea alta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Copa a 1 mano con mancuerna sentado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón al pecho abierto',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo con barra olímpica',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón abierto con barra recta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'21s con barra Z',	'N/A',	NULL,	4,	21,	40,	NULL,	'reps'),
(3,	'Martillos en banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Desplantes en maquina Smith',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(7,	'Femoral acostado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(7,	'Femoral sentado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(7,	'Femoral a una pierna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(7,	'Maquina de abductores / aductores',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales unilaterales mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales con mancuerna agarre supino',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales con mancuerna pesadas con ROM medio',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Flys con agarre neutro y agarre supino',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión de tríceps en polea alta con cuerda',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión en polea alta agarre neutro',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(7,	'Máquina de aductores',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Sentadilla perfecta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Prensa 90 grados',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Fondos sin asistencia',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(11,	'Elevación de talón en maquina de pie',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(11,	'Maquina de tibial anterior',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(11,	'Elevación unilateral de talón',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press banco horizontal con mancuernas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press en banco inclinado con barra olímpica',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press en maquina banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Peck deck en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo articulado bilateral',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Dominadas asistidas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales mancuernas apoyo banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales mancuerna de pie ROM medio',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Flys con mancuerna apoyo banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Remo con barra agarre abierto banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Frontales con mancuerna sentado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión con cuerda polea alta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión polea alta barra recta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Extensión de cuádriceps',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Patada en maquina horizontal',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(11,	'Elevación pantorrilla de pie en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(11,	'Elevación pantorrilla sentado maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl de bíceps mancuerna banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl de bíceps banco Scott peso integrado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl de bíceps tipo martillo mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Máquina abductores/aductores',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press banco inclinado con barra olímpica',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press banco declinado con barra olímpica',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press banco horizontal mancuerna + aperturas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Fondos en maquina asistida',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Lagartijas con elevación de pies',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión cuerda polea alta inclinación tronco',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión a una mano rotación codo',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(7,	'Peso muerto tradicional barra olímpica',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(7,	'Peso muerto mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(10,	'Prensa vertical',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(12,	'Maquina de aductores',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(11,	'Maquina tibial anterior',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(11,	'Elevación talón maquina pie',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Cables en polea alta 2 posiciones',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press inclinado maquina articulada',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Peck deck en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo cerrado en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón en maquina articulada bilateral',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Pull over hincado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales mancuerna sentado neutro',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Press maquina articulada',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Flys a una mano en polea baja',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl con barra Z en banco Scott',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl con cables en polea alta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Martillos con mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Prensa horizontal',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(12,	'Máquina de abductores y aductores',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(7,	'Sentadilla sumo en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Flys en banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales mancuerna apoyo banco inclinado de pie',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales 21s con mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Frontales con rotación de codo mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Press en maquina tipo hammer',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón abierto en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón articulado peso libre',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo T en maquina agarre cerrado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Pull over con apoyo en banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Aperturas banco horizontal mancuernas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Cables en jaula 3 posiciones',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Maquina con ligera declinación',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Cables en polea alta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales con mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Fondos en maquina con lastre',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón en maquina articulado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl de bíceps barra olímpica',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Martillos apoyo banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl en maquina Scott',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press militar en maquina articulada cerrado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Cables en jaula inclinación tronco',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Press militar maquina tipo hammer',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión triangulo polea alta inclinación',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión unilateral polea alta supino',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Press banco plano agarre cerrado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Extensión cuádriceps unilateral',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Sentadilla Smith',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press horizontal en maquina 2 agarres',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press en maquina hammer declinada',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales ligera inclinación tronco',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo polea alta con cuerda',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo maquina polea baja',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo polea baja barra recta pies elevados',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press banco horizontal maquina articulada',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales pesadas ROM medio',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión cuerda polea alta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón al pecho cerrado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón cruzado cables deltoides posterior',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Hiperextensión maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl bíceps supino',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl bíceps barra “Z”',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl bíceps cuerda polea baja',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Movimiento enfoque manguito rotador',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Remo al mentón mancuernas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales mancuerna 3 pesos',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Peck fly deltoides posterior',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Jalón cuerda polea alta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Press militar agarre neutro mancuernas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón polea alta unilateral',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón polea alta barra recta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Peso muerto maquina Smith',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Step up maquina Smith',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Patada con grilletes',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl bíceps polea baja barra recta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales + frontales mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Contracción trapecio maquina Smith',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Peck fly polea alta unilateral',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Frontales mancuerna parciales + completas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Peck fly polea baja banco horizontal',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press inclinado maquina unilateral',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press horizontal maquina unilateral',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Pull over mancuerna banco horizontal',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión barra recta polea alta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión 1 mano polea alta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(13,	'Crunch banco declinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(11,	'Elevación talón sentado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Press militar maquina unilateral',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Vuelos mancuerna deltoides posterior',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Jalón mentón polea alta barra',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Dominadas sin asistencia',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo Dorian maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl mancuernas pronación',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl polea alta 1 mano',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl polea baja tumbado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl mancuernas supinación final',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Press francés banco horizontal barra z',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión 1 mano mancuerna banco horizontal',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Lagartijas manos cerradas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Patada polea baja agarre supino',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(13,	'Crunch maquina peso integrado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Sentadilla libre',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(7,	'Peso muerto sumo barra libre',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Sentadilla con inclinación',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón 1 mano polea alta costado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo maquina articulada peso libre',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo Gironda',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Pull down abierto',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Pull dowm cerrado en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo T en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Hip thrust en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl spider con mancuernas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión con cuerda en polea alta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión individual polea alta supinación',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión polea alta barra supinación',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Cruce de poleas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press inclinado en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(8,	'Femoral sentado individual maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Jalón polea alta enfoque deltoides post',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales con mancuerna en banco',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Frontal polea baja individual',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo con mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalon lateral polea alta dorsal ancho',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo abierto en polea baja',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión polea alta detrás de cabeza',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Prensa española',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(8,	'Peso muerto rumano con barra',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(8,	'Femoral a 1 pierna en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Abducción wn maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Rack pull con barra',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Peck deck en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Press vertical en maquina hammer',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Flys o pájaros con mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Remo al mentón con barra',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales agarre neutro',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales en polea baja',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Press militar con mancuernas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl spider con barra',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión individual en pronación',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Cruce de poleas clavículas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press inclinado con barra',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Fondos en maquina asistida',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo articulado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo en polea baja cerrado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Hip thrust con barra',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Patada pendular en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Sentadilla hack',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Maquina de aductores',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión con cuerda en polea baja',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Copa mancuerna individual',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales en agarre neutro',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Frontal con cuerda en polea baja',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Sentadilla sissy',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Flys con mancuerna en banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Remo individual maquina articulada hombro post',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Pull over con triangulo',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl de bíceps con mancuerna en supino',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl de bíceps polea baja barra recta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión polea baja cuerda (tríceps)',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press hammer declinado individual',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Peck fly en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Máquina de abducción',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(6,	'Patada de glúteo en maquina pendular',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales mancuerna pecho recargado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Laterales polea baja con grilletes',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Frontal polea baja individual pronación',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl martillo con mancuernas sentado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Desplantes estáticos con mancuerna',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(9,	'Prensa 45 grados',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl predicador en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(4,	'Extensión vertical en maquina (tríceps)',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press inclinado con mancuernas',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press horizontal en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Cruce de poleas ángulo clavicular',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Abducción de hombro en polea media',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(5,	'Abducción con mancuernas banco inclinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón abierto en polea alta',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Remo Dorian individual',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Pull over con cuerda',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Press horizontal maquina o barra',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(1,	'Peck fly en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(2,	'Jalón cerrado en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(3,	'Curl de bíceps en polea baja con barra',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(13,	'Crunch en maquina',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(13,	'Crunch de costado (oblicuos)',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(13,	'Elevación de piernas en banco declinado',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(13,	'Hipopresivos',	'N/A',	NULL,	4,	10,	40,	NULL,	'time'),
(14,	'Elevación de talón de pie con extensión de rodilla',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(14,	'Elevación de talón con flexión de rodilla',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(14,	'Extensión de gemelos en prensa horizontal',	'N/A',	'',	4,	NULL,	40,	NULL,	'reps'),
(15,	'Maquina escalera',	'N/A',	NULL,	NULL,	NULL,	NULL,	NULL,	'time');
